/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**DNS response to a DNS request. */
export interface AddressResponse {
  address: string
  family: number
}
/**Perform a DNS lookup for the hostname, returning addresses in the request family. */
export function lookup(hostname: string, family?: number | undefined | null): Promise<AddressResponse>
